Style/Documentation:
  Enabled: false
StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Rails:
  Enabled: true
Rails/HasManyOrHasOneDependent:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
AllCops:
  Exclude:
    - '**/Gemfile'
